### ISSUE TITLE
Enums always get id=0

### ISSUE THREAD

**Issue by paradogz** [rpav/c2ffi#14]
Example input:
```
enum Enum1 { A, B, C };
enum Enum2 { D, E };

class Class1
{
enum Enum3 { F, G, H };
};
```

Output:
```
[
{ "tag": "enum", "ns": 0, "name": "Enum1", "id": 0, "location": "enum_test.h:1:6", "fields": [{ "tag": "field", "name": "A", "value": 0 }, { "tag": "field", "name": "B", "value": 1 }, { "tag": "field", "name": "C", "value": 2 }] },
{ "tag": "enum", "ns": 0, "name": "Enum2", "id": 0, "location": "enum_test.h:2:6", "fields": [{ "tag": "field", "name": "D", "value": 0 }, { "tag": "field", "name": "E", "value": 1 }] },
{ "tag": "class", "ns": 0, "name": "Class1", "id": 1, "location": "enum_test.h:4:7", "bit-size": 8, "bit-alignment": 8, "parents": [], "fields": [], "methods": [] },
{ "tag": "enum", "ns": 1, "name": "Enum3", "id": 0, "location": "enum_test.h:6:6", "fields": [{ "tag": "field", "name": "F", "value": 0 }, { "tag": "field", "name": "G", "value": 1 }, { "tag": "field", "name": "H", "value": 2 }] }
]
```

using llvm 3.5

**Comment by paradogz** [comment]
In addition, when enum is a function parameter, it gets full in-place fields description (just like the declaration) which can be omitted IMHO

**Comment by rpav** [comment]
This is/was sortof-as-intended; everything not-anonymous gets ID 0.  There was some reason for making all classes have an ID...

**Comment by rpav** [comment]
That should definitely be omitted!

**Comment by paradogz** [comment]
ok, then how json parser is supposed to find a referenced class/struct/etc? By name and ns?

**Comment by rpav** [comment]
That was the intent; if id=0, you use the name.  I've never been particularly convinced this was a great way to do things, though.  I can probably change it.  The only issue is code that may depend on the value as an "anonymous check," but since the C++ stuff already breaks that, it might as well all go in that direction.

**Comment by paradogz** [comment]
I see now. I like id-for-everything approach better, but the current one is also quite ok.
So feel free to close this issue whether you change this behavior or not.

**Comment by rpav** [comment]
Honestly I do too and like everything probably should have done it from the get-go.  It only gets worse with namespaces, because you can no longer *just* check the name, but you also have to keep a "composite key" with the NS.  With an ID, you don't.

I'll fix this; it may be a few days before I get the time though.

**Comment by rpav** [comment]
This is actually probably not going to change in the near future.
