### ISSUE TITLE
char16_t* parameter type gets replaced with int*

### ISSUE THREAD

**Issue by paradogz** [rpav/c2ffi#15]
This way strings become integers :)

Another thing is the representation of two-word types, which are written as `:unsigned-int`, `:unsigned-char` etc. Is there a special reason for not using the original type name?

**Comment by rpav** [comment]
Doh, sorry, fell off my radar.  Also, can you provide context?  Given the latest c2ffi:

```c++
struct Foo {
    char16_t *string;
    int len;
};

void foo(char16_t *x);
```

```console
$ c2ffi -x c++ --std c++11 test.hpp
```

```json
[
{ "tag": "struct", "ns": 0, "name": "Foo", "id": 1, "location": "test.hpp:1:8", "bit-size": 128, "bit-alignment": 64, "parents": [], "fields": [{ "tag": "field", "name": "string", "bit-offset": 0, "bit-size": 64, "bit-alignment": 64, "type": { "tag": ":pointer", "type": { "tag": ":char16_t" } } }, { "tag": "field", "name": "len", "bit-offset": 64, "bit-size": 32, "bit-alignment": 32, "type": { "tag": ":int" } }], "methods": [] },
{ "tag": "function", "name": "foo", "location": "test.hpp:6:6", "variadic": false, "inline": false, "storage_class": "none", "parameters": [{ "tag": "parameter", "name": "x", "type": { "tag": ":pointer", "type": { "tag": ":char16_t" } } }], "return-type": { "tag": ":void" } }
]
```

Note that, if you're *not* using C++11, then `:char16_t` is not a valid basic type, and will likely be a typedef of something else.  I'm not sure why you're seeing `int`, though, which is why context is required.

As for the naming convention of two-word types, I'm not entirely certain what you're objecting to; however you should be able to safely replace "-" in such names with a space.  I did not want to imply further type name parsing was necessary.

**Comment by paradogz** [comment]
I've retested it and you are right, char16_t is parsed nicely. Probably I had json from an older c2fii without c++11 option.

This also removes the second question, I'll try doing replacement as you suggest.
