### ISSUE TITLE
emitted json wrong for typedef'd inline anonymous enum?

### ISSUE THREAD

**Issue by attila-lendvai** [rpav/c2ffi#25]
shouldn't the inline anonymous enum be in the typedef's type under the tag "enum", symmetrically with struct's? 

input:

```
typedef enum
{
    SDL_FALSE = 0,
    SDL_TRUE = 1
} SDL_bool;
```

output:

```[
  {
    "fields": [
      {
        "value": 0,
        "name": "SDL_FALSE",
        "tag": "field"
      },
      {
        "value": 1,
        "name": "SDL_TRUE",
        "tag": "field"
      }
    ],
    "location": "\/usr\/include\/SDL2\/SDL_stdinc.h:116:9",
    "id": 45,
    "name": "",
    "ns": 0,
    "tag": "enum"
  },
  {
    "type": {
      "id": 45,
      "name": "",
      "tag": ":enum"
    },
    "location": "\/usr\/include\/SDL2\/SDL_stdinc.h:120:3",
    "name": "SDL_bool",
    "ns": 0,
    "tag": "typedef"
  }
]```

**Comment by rpav** [comment]
This appears to be entirely dependent on what mood clang is in.  It changes considerably based on context, e.g.:

```c
typedef struct foo { char a; } bar;
typedef enum { A, B } quux;
```

In this case, both get inlined.  But remove the `typedef struct`, and the enum is not inlined.  Variations on this will produce different definitions as well (try `typedef struct foo bar`).  But c2ffi merely processes the AST as passed by clang.

Ultimately it's necessary to handle either form identically, because there are things like:

```c
struct foo {
  struct { ... } a, b;
};
```

This leads to an anonymous struct reference from `b` via id rather than being inlined.

**Comment by attila-lendvai** [comment]
oh, so ID's are integer identifiers for anonymous types? IOW, i shouldn't rely on the nestedness in the json output, but rather use id's to connect unnamed definitions?

**Comment by attila-lendvai** [comment]
oh, now i know what those id's are for! :)

i've reworked the code to use them, thanks!

**Comment by rpav** [comment]
Closing.

**Comment by attila-lendvai** [comment]
thanks!
