### ISSUE TITLE
Weird error compiling via docker

### ISSUE THREAD

**Issue by stathissideris** [rpav/c2ffi#27]
I'd like to contribute a Dockerfile for c2ffi, but I have trouble compiling. I use the attached Docker file (still a bit messy, I'm in the middle of trying different things) and I get this error during linking:

```
/usr/bin/ld: /usr/lib/llvm-3.7/bin/../lib/libclangAST.a(DeclCXX.o): undefined reference to symbol '_ZN4llvm19SmallPtrSetImplBase16shrink_and_clearEv'
//usr/lib/x86_64-linux-gnu/libLLVM-3.7.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've tried several different approaches, but I always get stuck. As you can see, I didn't compile LLVM and clang, but I used the packages from LLVM to install version 3.7.1 specifically from http://llvm.org/apt/
[Dockerfile.txt](https://github.com/rpav/c2ffi/files/93603/Dockerfile.txt)

**Comment by rpav** [comment]
In every instance I've seen similar errors, it was because there were "wrong" libraries hanging around from another version of LLVM or Clang.  I don't know what the base install looks like, but this is Clang missing LLVM symbols, so there is a library conflict somehow.  The last time, there were old /usr/lib/libLLVM*.so still around, as I recall.

Interesting to note there are "official" packages though!  And that they seem to compile c2ffi.

Note, you should probably `git checkout -b ${llvm_release}` (assuming it works that way) rather than a specific commit, because the branch may be updated regularly with bugfixes etc.  The packages already appear to be nightly builds, so you shouldn't be losing much.

Once this works, let me know and I'll link/include it!  (Let me know what's useful, I'm not terribly familiar with Docker.)  Seems like a good/quick way to get everything built.

**Comment by stathissideris** [comment]
Thanks for your help, I'll experiment a bit more and see if I can get it to work properly. What flavour of linux do you normally compile c2ffi on? It would be easy to switch to a different distribution.

This approach, apart from being an easy/clean way to build c2ffi, would also be a good way to distribute and quickly use it. Once ready, I could upload the Docker image to DockerHub and (if you have Docker installed), it would be possible in one step to obtain c2ffi and all its dependencies, and run it with a single command like `docker run stathissideris/c2ffi ...`. The host system would not even need to have clang installed.

**Comment by rpav** [comment]
Not terribly helpfully, Gentoo (because I build the system with debug symbols etc).  That said, I <i>know</i> people have gotten it to work on other systems, at least, after similarly compiling LLVM manually.  Ubuntu would be a nice choice for simplicity.  If I get a chance in the next day or so I'll try booting a VM and see what it looks like.

**Comment by stathissideris** [comment]
An alternative approach to going into the trouble of setting up a VM (and possibly quicker) would be to install docker, get my Docker file (save it an empty folder as `Dockerfile`), `cd` to the folder and run `docker build .`. That would give you Ubuntu in a container and attempt to build cffi.

**Comment by rpav** [comment]
Sure, though, as I am unfamiliar with Docker except in a general sense, one variable at a time. ;)  Good excuse to play with Docker if I can get it working in a VM, though.

**Comment by stathissideris** [comment]
Agreed about messing with one variable at a time, but the whole point of docker is to remove the need for VMs. But maybe you prefer to experiment with new tech in VMs before "contaminating" your real system with them!

**Comment by xaduha** [comment]
Same issue building it on Voidlinux.

**Comment by rpav** [comment]
To see _exactly_ what clang/ld are attempting, use the following.  **Please don't paste the output here**, link a <a href="gist.github.com">gist</a> or something.  Really, you should be able to search through it and find what's not getting linked correctly.

``` console
$ cmake -DCMAKE_EXE_LINKER_FLAGS="-v -Wl,--verbose" .
 ...
$ make VERBOSE=1
```

Obviously adjust this as necessary (make -jN, any other linker flags you need, etc).

**Comment by ghost** [comment]
This looks suspiciously like the library link order error I was seeing.

**Comment by rpav** [comment]
OK after much too long, this should build out-of-the-box with Ubuntu clang-3.7.  Due to gcc's c++11 ABI stuff and the apparent fact Ubuntu's clang was compiled with g++, _clang cannot compile things using its own libraries on Ubuntu_.

However, if you use gcc this should now work, and I've adapted it to look for LLVM install paths.

@stathissideris: having finally gotten around to screwing with Docker at some point, and having _finally_ fixed this, I'll try out your build, though you probably no longer care. ;)

**Comment by stathissideris** [comment]
Hey thanks for fixing this, I have cloned c2ffi here https://github.com/stathissideris/c2ffi and I've added a Dockerfile that seems to work. After running `docker build .` in the docker folder, you can try:

`docker run --rm -ti cffi c2ffi/build/bin/c2ffi`

It's not quite ready for a pull request yet because I think I'm installing way too many things with apt, so I'll like to minimize it first and add some documentation on how to use it!
