### ISSUE TITLE
inline output of inline types

### ISSUE THREAD

**Issue by attila-lendvai** [rpav/c2ffi#40]
# the situation

in C you can have this:

```
typedef enum {
  a = 0,
  b
} typeName;
```

this is a C typedef with an inline definition of an anonymous enum. in the c2ffi json output it currently shows up as two separate entries, connected by the ID of the anonymous entry.
# the headache

cffi/c2ffi has a means to filter out definitions, and it would complicate the code that it needs to deal with the reconnection of these two json entries. the current kludge is to always emit every anonymous entry with a generated name.
# proposed solution

would it be possible for the json output to have the same structure as the C typedef, i.e. the anonymous type declaration to be nested inside the type field of the typedef json entry?
# references

the cffi issue: https://github.com/cffi/cffi/pull/107
cffi-dev mail (cffi needs patching to support this): https://mailman.common-lisp.net/pipermail/cffi-devel/2016-October/003007.html

**Comment by rpav** [comment]
Not trivially, because clang parses and spits out the `enum` definition first, and `c2ffi` doesn't do any postprocessing.  But even if it did, there is no general solution for this.  You _must_ preprocess and handle anonymous cases properly, or you cannot generate correct definitions for all cases anyway, e.g.:

``` c
struct X {
   struct { ... } a, b;
};
```

This is one of numerous cases that requires cross referencing no matter what you do, and once you have it, things like `typedef` should no longer be an issue.

**Comment by attila-lendvai** [comment]
that struct example is indeed a nasty C feature in this context, because of the multiple struct members referencing the same anon struct def.

ok, so this won't work... :(

thanks though!
