### ISSUE TITLE
Macro defs not working

### ISSUE THREAD

**Issue by porky11** [rpav/c2ffi#42]
It should be possible also to get definitions as in #define, using "--with-macro-defs" but that's not the case.

**Comment by rpav** [comment]
You can, but I'm not sure what you're expecting.  The `--with-macro-defs` option works in conjunction with `-M <output-file.h>` to also output the `#define` and its original location in a comment.  The way to actually *get* macro definitions is to use `-M` and `--with-macro-defs` and then call `c2ffi` a second time on the output file.

It is also possible to produce the file *without* macro defs included, if you plan on `#include`-ing it along with the original files.  In this case, having the definitions included would be an error.

**Comment by porky11** [comment]
I thought, it would just add the macro definitions to the list of variable definitions, in the first call to c2ffi.
(why doesn't it work this way?)

**Comment by rpav** [comment]
Basically because it's not that simple.. you can have a preprocessor definition that looks like:

```c
#define FOO if(...) {
```

...or pretty much anything you want.  Many useful constants are also defined as C expressions, e.g. `(1<<5)`, masks, etc.  You would more or less need to implement C expression parsing and evaluation... alternatively, just use the existing C parser already on hand.

Except, you can't *just* throw the text of the `#define` at the compiler; in order to properly evaluate, you need some context, like what it's being assigned to.  Additionally, a lot of these can also use *other* previous `#define`'s.  Basically the preprocessor is a huge mess and extracting anything at all works surprisingly well as it is.

**Comment by porky11** [comment]
I would like to have an easy way to get all simple defines (just simple definitions like `#define GL_SOMETHING 0x0001`), but I don't think, there is a nice way.
Maybe it would be helpful to tag the defines as "macro"  instead of a calculated type would be helpful (when parsing opengl the types of the defines should be convertetd to GLenum, which is not the calculated type, but clear, since (almost?) all macros have this type )
