### ISSUE TITLE
Add include tags

### ISSUE THREAD

**Issue by porky11** [rpav/c2ffi#43]
If a file incldues another file, it would be helpful, to add a list tagged with "include" so a `#include "file.h"` could be converted to `<mylang_include> "file.mylang"` (and maybe even an option not to include files specified by `#include`, but I'm not sure, if this is possible, but since the location is given, it's not too difficult not to include unwanted files and recreate similar file partition as in original)

**Comment by rpav** [comment]
I'm not entirely sure what you're after here, but any filtering is likely not to be implemented on the c2ffi side.  Rather you should process this in your language/editor/etc and (ideally) redump to a smaller, more specific format.  This is primarily to keep c2ffi a small and simple tool, since different applications will likely have different needs, and rolling them all into varying options is likely to become unmaintainable.

Also there's not a ton of control over the preprocessor AFAICT; really there's not a *lot* of control over the entire process: you pretty much specify options you might on the commandline, feed it the file, and you get some AST to work with.  But filtering on source `#include` in your language should not be hard.
