### ISSUE TITLE
Meaning of NS 

### ISSUE THREAD

**Issue by stacksmith** [rpav/c2ffi#51]
Again, from the "doing fancy things with c2ffi" dept...

Types defined inside typedefs are sometimes translated into similar deep JSON structures, and other times, into separate and anonymous (non zero ID and non-zero NS?) definitions of the inner type followed by typedef definition referring to them by id.

- Could you shed some light on the meaning of NS values? As far as I can tell, anything non-zero means that a non-global scope is active, but the numeric values seem to be never referred to.

- IDs seem to be used by anonymous definitions and typedefs, but sometimes objects are assigned an ID even though there is a NAME present.  Is that the case only for inner definitions?

- IDs seem to be unique, except when they are 0.  There are a lot of entities with ID 0.  This makes IDs not particularly useful in say, enumerating entities.

**Comment by rpav** [comment]
* NS is purely a C++ construct I believe, but included for `ns=0` being the root namespace, and nonzero for other namespaces (which assign a namespace ID).
* ID is assigned to an anonymous type and used for anonymous typedefs; if there's a case where there is an actual typename *and* a non-zero ID, assuming it's not being typedef'd (but not including *using* that typedef), I forget
* Sure, IDs are only meant to track anonymous types; if I had it to redo I'd probably assign IDs for most types, but it would require changing a number of things.  You can/should implement your own indexing anyway, though, since your needs may not precisely map onto what makes sense for c2ffi (e.g., separate IDs for various things, a la `ns`).
