### ISSUE TITLE
Build fail with llvm 4.0.1 

### ISSUE THREAD

**Issue by borodust** [rpav/c2ffi#52]
With msys2 mingw64 environment:
git:
```bash
$git branch
* llvm-4.0.0
```
clang
```bash
$clang.exe --version
clang version 4.0.1 (https://llvm.org/git/clang 3c8961bedc65c9a15cbe67a2ef385a0938f7cfef) (http://llvm.org/git/llvm c8fccc53ed66d505898f8850bcc690c977a7c9a7)
Target: x86_64-w64-windows-gnu
Thread model: posix
```

Build log:
```
$ cmake --build .
Scanning dependencies of target c2ffi
[  7%] Building CXX object CMakeFiles/c2ffi.dir/src/AST.cpp.obj
[ 15%] Building CXX object CMakeFiles/c2ffi.dir/src/Decl.cpp.obj
[ 23%] Building CXX object CMakeFiles/c2ffi.dir/src/Expr.cpp.obj
[ 30%] Building CXX object CMakeFiles/c2ffi.dir/src/OutputDriver.cpp.obj
[ 38%] Building CXX object CMakeFiles/c2ffi.dir/src/Template.cpp.obj
[ 46%] Building CXX object CMakeFiles/c2ffi.dir/src/Type.cpp.obj
[ 53%] Building CXX object CMakeFiles/c2ffi.dir/src/c2ffi.cpp.obj
[ 61%] Building CXX object CMakeFiles/c2ffi.dir/src/init.cpp.obj
[ 69%] Building CXX object CMakeFiles/c2ffi.dir/src/options.cpp.obj
[ 76%] Building CXX object CMakeFiles/c2ffi.dir/src/drivers/JSON.cpp.obj
[ 84%] Building CXX object CMakeFiles/c2ffi.dir/src/drivers/Null.cpp.obj
[ 92%] Building CXX object CMakeFiles/c2ffi.dir/src/drivers/Sexp.cpp.obj
[100%] Linking CXX executable bin/c2ffi.exe
C:/msys64/opt/llvm40/lib/libclangDriver.a(MSVCToolChain.cpp.obj):MSVCToolChain.cpp:(.text+0x3e0b): undefined reference to `GetFileVersionInfoSizeW'
C:/msys64/opt/llvm40/lib/libclangDriver.a(MSVCToolChain.cpp.obj):MSVCToolChain.cpp:(.text+0x3e79): undefined reference to `GetFileVersionInfoW'
C:/msys64/opt/llvm40/lib/libclangDriver.a(MSVCToolChain.cpp.obj):MSVCToolChain.cpp:(.text+0x3ee9): undefined reference to `VerQueryValueW'
collect2.exe: error: ld returned 1 exit status
```

**Comment by borodust** [comment]
I should try to rebuild it with exactly 4.0.0, but this build version bump shouldn't probably break stuff.

**Comment by borodust** [comment]
Actually, after a second look at it, I might built llvm/clang in a weird way or smth. :sigh:

**Comment by borodust** [comment]
Solved by adding `version` library as a _last_ dependency to `target_link_libraries`

**Comment by ailisp** [comment]
@borodust Thanks for the point! You saved my evening! Also, can you list your whole building process here? Looks you don't given `-G "MSYS Makefiles` to cmake and also use clang to build. That looks magic, because for me only after given that option and using gcc to build will success. Otherwise, cmake will use MSVC by default. Clang will produce a lot of linker error, even if I set CMAKE_LINKER to clang's linker lld.exe. Can you list how you do that? Maybe helpful for other lispers on windows.
Here is my (messed up) steps:
1. install all match `pacman -Ss llvm` under mingw64 with version 5.0.0 (now is 5.0.0 version in msys2 by default)
2. `pacman -S mingw64/cmake`
3. add `version` as last dep to `target_link_libraries` in CMakeLists.txt (as you suggests)
4. (in build dir) `cmake -G "MSYS Makefiles" .. && make`
